### ISSUE TITLE
Update Smart Contract

### ISSUE THREAD

**Issue by kerrjatwit** [tomassurna/NoteTogether#19]
refactor smart contract to remove the user struct, use msg.sender rather than an input address, and general fixes.

**Comment by kerrjatwit** [comment]
accidentally pushed straight to main. Will be pushing to my personal branch in the future

**Comment by tomassurna** [comment]
https://github.com/tomassurna/NoteTogether/commit/8a642d0d77629798c24e24c69fc2e41d022ad6a8
