### ISSUE TITLE
Figure Out Analytics Data

### ISSUE THREAD

**Issue by tomassurna** [tomassurna/NoteTogether#25]
Create a list of what type of analytics data we can and want to keep track of.

**Comment by kerrjatwit** [comment]
Analytics Data

	Note Data
		timestamp and tag
		display by concentration of timestamp grouped by tag
		How?
			grab straight from UI when note is created
	View Data
		a view is a single session start to stop. 
			OnStart/OnPlay(non-buffered) triggers event that saves start timestamp
			OnPause triggers event that saves stop timestamp and export start+stop
			
		
		a seek is: (one or more of these)
			a) a single fast forward or rewind with timestamp before seek and after seek
				requires a constant monitor of current timestamp to determine "before seek" time
			b) a single timestamp of the seek destination
				easy to implement, doesn't represent what was skipped
		
		(option) a continuous view is a session uninterupted by a seek
			OnStart save start time
			OnSeek save end time export end time and save new start time
